config/routes.rb
Artchart::Application.routes.draw do
  root :to => 'home#index'

  resources :works, :only => [:index] do
    collection do
      get 'search'
    end
  end

  resources :locations, :only => [:show]

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name
  has_many :works
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  has_many :works
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :name, :location, :artist, :url
  belongs_to :artist
  belongs_to :location

  define_index do
    indexes name
    indexes location.name, :as => :location
    indexes artist.name, :as => :artist
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location = Location.find(params[:id])
    @works = @location.works.page(params[:page]).per_page(40)
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  
  def index
    @works = Work.page(params[:page]).per_page(40)
  end

  def search
    @works = Work.search(params['q'], :page => params[:page], :per_page => 40)
    render :action => :index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/home/index.html.erb
<div>
  Welcome to ArtChart, a database of artwork from around the globe and its location!
</div>

<div>
  <%= link_to 'View artwork listings', works_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artchart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<h2>Works at this location:</h2>
<table>
  <tr>
    <th>Name of work</th>
    <th>Artist</th>
  </tr>

  <%= render :partial => 'works/work', :collection => @works, :locals => {:show_location => false} %>
</table>

<%= will_paginate @works %>

app/views/works/_work.html.erb
<% show_location = true if local_assigns[:show_location].nil? %>
<tr>
  <td><%= link_to work.name, work.url %></td>
  <td><%= work.artist.name %></td>
  <% if show_location %>
    <td><%= link_to work.location.name, location_path(work.location.id) %></td>
  <% end %>
</tr>

app/views/works/index.html.erb
<%= form_tag({:action => :search}, {:method => 'get'}) do %>
Search: <%= text_field_tag :q, params[:q], :size => 40 %> <%= submit_tag 'Go' %>
<% end %>
<table>
  <tr>
    <th>Name of work</th>
    <th>Artist</th>
    <th>Location</th>
  </tr>

  <%= render :partial => 'work', :collection => @works %>
</table>

<%= will_paginate @works %>